const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const src=fs.readFileSync(require('node:path').join(__dirname,'../js/notifications.js'),'utf8');
const at=h=>new Date(2026,9,6,h), key=d=>new Date(d).toLocaleDateString('en-CA');
let delivered=0;
const data={settings:{notify:true,studyReminders:true,dailyGoal:180},sessions:[],tasks:[],timer:null};
const reg={showNotification:async()=>{delivered++;},getNotifications:async()=>[]};
const ctx={URL,Date,window:{Notification:{}},Notification:{permission:'granted'},location:{href:'https://example.test/Hazal-cal-sma-/'},Store:{data,save(){}},U:{dateKey:key},navigator:{serviceWorker:{getRegistration:async()=>reg}},document:{hidden:true},setInterval(){},Messages:{get:k=>k}};
vm.createContext(ctx);vm.runInContext(src,ctx);const n=ctx.window.LunaNotify;
assert.equal(n.choose(data,at(8)),null);assert.equal(n.choose(data,at(22)),null);
assert.equal(n.choose(data,at(17)).kind,'remindStart');
data.timer={running:true};assert.equal(n.choose(data,at(18)),null);
data.timer={phase:'focus',accum:60000,pausedAt:+at(16)};assert.equal(n.choose(data,at(17)).kind,'remindPaused');
data.timer=null;data.sessions=[{end:+at(15),minutes:45}];assert.equal(n.choose(data,at(18)).vars.minutes,135);
data.tasks=[{done:false,due:key(at(18))}];assert.equal(n.choose(data,at(18)).kind,'remindTasks');
data.tasks[0].done=true;data.sessions[0].minutes=180;assert.equal(n.choose(data,at(18),+at(12)).kind,'remindAway');
data.settings.studyReminders=false;assert.equal(n.choose(data,at(18)),null);
assert.equal(n.options('test').icon,'https://example.test/Hazal-cal-sma-/icons/luna-notification-v2.png');
assert.equal(n.options('test').badge,'https://example.test/Hazal-cal-sma-/icons/luna-notification-v2.png');
(async()=>{assert.equal(await n.send('Luna','test'),true);assert.equal(delivered,1);ctx.Notification.permission='denied';assert.equal(await n.send('Luna','test'),false);assert.equal(delivered,1);console.log('14 notification assertions passed');})().catch(e=>{console.error(e);process.exitCode=1;});